### ISSUE TITLE
Violation of the GNU Public License

### ISSUE THREAD

**Issue by VideoGameSmash12** [GriefUnion/BetterMeteor#1]
If it wasn't obvious from the source code, this project is a fork of Meteor Client, which is currently licensed under the GNU Public License (GPLv3 to be exact). Your fork is in violation of this license, primarily because you removed the LICENSE file. You cannot change the license of a fork of a GPLv3-licensed project that is not yours, as noted in this excerpt from the license itself:

> You may convey a work based on the Program, or the modifications to produce it from the Program, in the form of source code under the terms of section 4, provided that you also meet all of these conditions:
> * The work must carry prominent notices stating that you modified it, and giving a relevant date.
> * **The work must carry prominent notices stating that it is released under this License and any conditions added under section 7. This requirement modifies the requirement in section 4 to “keep intact all notices”.**
> * ***You must license the entire work, as a whole, under this License to anyone who comes into possession of a copy.* This License will therefore apply, along with any applicable section 7 additional terms, to the whole of the work, and all its parts, regardless of how they are packaged. *This License gives no permission to license the work in any other way, but it does not invalidate such permission if you have separately received it.***

**Comment by GriefUnion** [comment]
Im on vacation rn

**Comment by GriefUnion** [comment]
Idfk if i copy pasted it right
